In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [6]:
arr=np.array([1,2,3,])
arr_2d = np.array([[1,2,3],[4,5,6]])
np.zeros((3,3))
np.ones((2,4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)

array([[-1.30631369,  0.55797228],
       [ 0.16963947,  0.61178764],
       [-0.10817396,  0.357803  ]])

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b
a*b
np.sin(a)
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
np.dot(A,B)
A @ B

array([[19, 22],
       [43, 50]])

In [9]:
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()

np.float64(1.118033988749895)

In [10]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]
arr[1:4]
arr[::2]
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0,1]
arr[:,1]
arr[1,:2]

array([4, 5])

In [11]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr>3
arr[mask]

array([4, 5])

In [12]:
arr = np.arange(6)
arr.reshape(2, 3)
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

In [13]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]


array([6, 7, 8])

In [15]:
np.save('array.npy', arr)
loaded_arr = np.load('array.npy')
